### ISSUE TITLE
Unable to write file on ecrypted directory with zero-ed key

### ISSUE THREAD

**Issue by comio** [google/fscryptctl#14]

**Comment by comio** [comment]
Hi,

I'm trying to investigate the fscryptctl usage on my Gentoo Linux system. It seems to not work at all. I tried to load key and set policy using fscryptctl as well as using e4crypt tool.
Adding key with e4crypt (used as passphrase) works well, instead loading key with fscryptctl doesn't work.

Do you have any suggestion?

Thanks,

Luigi

My session log:

```
$ uname -a
Linux gentoobox 4.20.0-gentoo #1 SMP Mon Dec 24 18:29:34 CET 2018 x86_64 Intel(R) Pentium(R) CPU N3700 @ 1.60GHz GenuineIntel GNU/Linux

$ keyctl show
Session Keyring
1002831468 --alswrv      0     0  keyring: _ses
 763117039 ----s-rv      0     0   \_ user: invocation_id

$ fscryptctl insert_key --ext4 < ../key.key 
f574a77464017311

$ mkdir test_fscryptctl

$ fscryptctl set_policy f574a77464017311 test_fscryptctl

$ echo "Hello world!" > test_fscryptctl/test.txt
-bash: test_fscryptctl/test.txt: Argomento non valido

$ touch test_fscryptctl/test2.txt
touch: impostazione degli orari di 'test_fscryptctl/test2.txt': File o directory non esistente

comio@gentoobox /media/deluge/working $ ls test_fscryptctl/

$ cat ../key.key |e4crypt add_key
Enter passphrase (echo disabled): 
Added key with descriptor [d5b9ede6096eb0a8]

$ keyctl show
Session Keyring
1002831468 --alswrv      0     0  keyring: _ses
 763117039 ----s-rv      0     0   \_ user: invocation_id
 929870589 --alsw-v   1000   100   \_ logon: ext4:d5b9ede6096eb0a8
 615005273 --alsw-v   1000   100   \_ logon: ext4:f574a77464017311

$ mkdir test_e4crypt

$ fscryptctl set_policy d5b9ede6096eb0a8 test_e4crypt/

$ echo "Hello world!" > test_e4crypt/test.txt

$ touch test_e4crypt/test2.txt

$ ls test_e4crypt/
test2.txt  test.txt
```

**Comment by comio** [comment]
My key was a 0-filled stream. I suppose an issue at ext4 level. Changing with a true random key, it seems to work.

**Comment by ebiggers** [comment]
For future reference, this issue was specific to v1 encryption policies that use AES-256-XTS; it was caused by the two halves of the AES-256-XTS keys being identical which is not allowed.  `fscryptctl` v1.0 only supports v2 encryption policies, which don't have this quirk and will accept an all-zeros key, due to the use of a new key derivation function which results in the halves of the AES-256-XTS keys differing even if the halves of the input key are the same.

That being said, it obviously doesn't make sense to use an all-zeroes key, except possibly for testing.
