### ISSUE TITLE
fscryptctl compatibilty with mkfs.ubifs

### ISSUE THREAD

**Issue by embetrix** [google/fscryptctl#33]
hello I'm using fscryptctl v1.0.0 with an UBIFS on a RAW Nand Flash with a 5.10 kernel  and mtd-utils 2.1.4:

1. Create an encrypted ubifs using mkfs.ubifs  as follow:

```
# dd if=/dev/urandom of=key.data count=64 bs=1
# mkdir -p rootfs/somedir
# echo "somedata" > rootfs/somedir/somefile
# mkfs.ubifs -m 4096 -e 253952 -c 4068  --cipher AES-256-XTS --key key.data -r rootfs  rootfs.ubifs                                                                    
mkfs.ubifs: fscrypt master key descriptor: 0x0dbfd8a3ba6c7e60 
```

2. Update ubifs volume:
```
# ubiupdatevol /dev/ubi0_2 -t                                                                                       
# ubiupdatevol /dev/ubi0_2 rootfs.ubifs  
```

3. Mount volume:
```
# mount -t ubifs  /dev/ubi0_2 /mnt 
# ls -l /mnt/                                                                                                       
drwxr-xr-x    2 root     root           232 Oct 29 17:44 9r,9Ko40w3Qg8kg9l3457CjT40nHIhWD 
```
4. Decrypt volume:

```
# fscryptctl add_key /mnt < key.data                                                                                
77120bc70608b4aec343dc803a9a695c                                                                                                            
# ls -l /mnt/                                                                                                       
drwxr-xr-x    2 root     root           232 Oct 29 17:44 9r,9Ko40w3Qg8kg9l3457CjT40nHIhWD  
```

It doesn't look that the decryption is working !!

**Comment by embetrix** [comment]
it likes like the decryption is working only for a short moment then lost:

```
# umount /mnt
# mount -t ubifs /dev/ubi0_2 /mnt && fscryptctl add_key /mnt < key.data && ls -l /mnt                              
77120bc70608b4aec343dc803a9a695c                                                                                                            
ls: /mnt/somedir: No such file or directory                                                                                                 
# ls -l /mnt/                                                                                                       
drwxr-xr-x    2 root     root           232 Oct 29 17:44 ?2 ????????x?D??
```

**Comment by embetrix** [comment]
kernel dmesg looks normal with no errors:

```
 5544.209824] UBIFS (ubi0:2): un-mount UBI device 0                                                                                        
[ 5544.209874] UBIFS (ubi0:2): background thread "ubifs_bgt0_2" stops                                                                       
[ 5558.750595] UBIFS (ubi0:2): Mounting in unauthenticated mode                                                                             
[ 5558.750991] UBIFS (ubi0:2): background thread "ubifs_bgt0_2" started, PID 1530                                                           
[ 5558.833237] UBIFS (ubi0:2): UBIFS: mounted UBI device 0, volume 2, name "rootfs"                                                         
[ 5558.833267] UBIFS (ubi0:2): LEB size: 253952 bytes (248 KiB), min./max. I/O unit sizes: 4096 bytes/4096 bytes                            
[ 5558.833284] UBIFS (ubi0:2): FS size: 396165120 bytes (377 MiB, 1560 LEBs), journal size 9404416 bytes (8 MiB, 38 LEBs)                   
[ 5558.833295] UBIFS (ubi0:2): reserved for root: 0 bytes (0 KiB)                                                                           
[ 5558.833313] UBIFS (ubi0:2): media format: w5/r0 (latest is w5/r0), UUID 1081076B-E411-4435-86F5-BD23DFC796B9, small LPT model  
```

**Comment by ebiggers** [comment]
I don't understand.  Where in your example did you ever create an encrypted directory (`fscryptctl set_policy`)?

**Comment by embetrix** [comment]
@ebiggers no as I said the encryption is done using mkfs.ubifs

some how it did work on older releases: https://patchwork.ozlabs.org/project/linux-mtd/cover/20181018143718.26298-1-richard@nod.at/

**Comment by ebiggers** [comment]
It looks like `mkfs.ubifs` is outdated and is hardcoded to assume v1 encryption policies.

Please report this to the developers of `mkfs.ubifs`.  There's nothing the developers of `fscryptctl` can do about this.

Or better yet, just use `fscryptctl set_policy`.

**Comment by embetrix** [comment]
@ebiggers I don't get where the v1 encryption policies are involved with mkfs.ubifs ?!
please read my comments above the decryption seems to be working for a short time.

**Comment by ebiggers** [comment]
I don't see any evidence that decryption ever worked.  It can't, because the crypto is fundamentally different between v1 and v2 encryption policies.

What the `mkfs.ubifs` developers have done is hard-coded the old v1 format into their mkfs tool, without telling us, and then not updating it to support v2.  So it just is not going to work.

You can use an older version of `fscryptctl` if you want to; we made the switch from v1 to v2 in `fscryptctl` v1.0.0.  But keep in mind there is a reason we dropped v1 support, and you probably will encounter known problems with v1.  And if you report them to us, we will simply tell you that the fix is to upgrade to v2.

A much better idea would be to just create your encrypted directory in the actually supported way, which is to use `fscryptctl set_policy`.  It's not reasonable to have the low-level details of kernel filesystem encryption hard-coded into third-party tools outside of test code, anyway.  That leads to exactly this sort of problem...

**Comment by embetrix** [comment]
@ebiggers the reason behind this setup is that I would like to enable authentication of ubifs by signing offline with an asymetric key

**Comment by embetrix** [comment]
@AgentD

**Comment by ebiggers** [comment]
UBIFS authentication is a separate feature.

I don't see why using UBIFS authentication would require that `mkfs.ubifs` sets up the encryption.

**Comment by embetrix** [comment]
I want to have a readonly UBIFS encrypted and signed offline with mkfs.ubfis

```
mkfs.ubifs -m 4096 -e 253952 -c 4068  \
           --hash-algo sha256 --auth-key ubifs.key --auth-cert ubifs.crt \
           --cipher AES-256-XTS --key ubifs-enc.key -r rootfs  rootfs.ubifs
```

**Comment by richardweinberger** [comment]
So you have dropped v1 support from fscryptctl because you assumed that no user space tool will ever create a an fscrypt encrypted filesystem image?
`mkfs.ubifs` does so, that's a common requirement for (deeply) embedded systems.
Looks like we better add our own fscrypt user space tooling to mtd-utils, @AgentD.
Even after adding v2 support, we still need to keep v1 users happy.

**Comment by ebiggers** [comment]
There were many reasons to drop support for v1 policies in `fscryptctl`.  It prevents users from accidentally using v1 and running into the known problems and limitations with it, and it greatly simplified the `fscryptctl` codebase.  In fact both you and @embetrix have run into into the known problems with v1 policies and requested that they be fixed: https://github.com/google/fscryptctl/issues/15 and https://lore.kernel.org/linux-fsdevel/657b45e3-322d-44c4-1ea6-e43ff76be785@nod.at/T/#u.  Well, we did that.

Users can also still choose to use an older version of `fscryptctl`, as I mentioned, and was mentioned in the `fscryptctl` v1.0.0 release notes from February 2021.  v1 policy support hasn't been dropped from the kernel.

If you are committed to maintaining code in `mtd-utils` that replicates all the key derivation, encryption, and other things the kernel does, that's your choice, but you should be keeping it up to date and not insisting on staying on an old version forever.

**Comment by richardweinberger** [comment]
@ebiggers I'm well aware about the limitations of v1, no need to worry. I also agree that adding v2 support to `mkfs.ubifs` overdue.
But dropping v1 from fscryptctl is IMHO a bold move.
Sure people can use an old version but that's not really pleasant, especially on ecosystems where new versions are automatically chosen.

**Comment by ebiggers** [comment]
Maybe it was.  But it happened over a year and a half ago.  It seems a bit late to go back and re-add it now.  There aren't many users of `fscryptctl`, and if anyone else ran into issues with the removal of v1 policy support (this is the first complaint), they must have already done the work to upgrade to v2 policies or to package an older version of `fscryptctl`.

Also keep in mind is that re-adding v1 policy support would bloat the binary size, e.g. due to the SHA-512 implementation needed.  Not ideal for embedded systems, which are a target of `fscryptctl`.

Finally, this issue is just about creating new filesystems, with a kernel version that supports v2 policies.  In this case, there is really no good reason to not use v2.

**Comment by richardweinberger** [comment]
> to summarize : using an offline fscrypt encrypted rootfs with systemd as init is actually and was never possible !

Sure it is, just setup fscrypt in your initramfs. But this is off topic here.
